### ISSUE TITLE
Request: Extra chapters

### ISSUE THREAD

**Issue by IsaacGraham** [fallaciousreasoning/apracticalguidetoevil#3]
Hi, would it be feasible to add the extra chapters in here, ideally inserted into the story when they were published?

**Comment by fallaciousreasoning** [comment]
@IsaacGraham would you mind checking if the extra chapters are in there? I reran the scraper recently, so it might've added them.

**Comment by IsaacGraham** [comment]
Nope they're not in there, but how recently do you mean? The last commit was 3 months ago which was about the time I started reading.

**Comment by IsaacGraham** [comment]
I ended up finding another github repo that had the extra chapters included. GabbyNEW/APGtE_Scraper

**Comment by fallaciousreasoning** [comment]
👍 sweet, mind adding a link here, so if anyone else is looking they can find it easily?

**Comment by IsaacGraham** [comment]
https://github.com/GabbyNEW/APGtE_Scraper
