### ISSUE TITLE
Practical Guide to Evil has Ended

### ISSUE THREAD

**Issue by GregorDeVillain** [fallaciousreasoning/apracticalguidetoevil#4]
Greetings! Given that a practical guide to evil has ended with finality, could you please update the file to include it in its entirety? Thank you very much for the help!😊

**Comment by fallaciousreasoning** [comment]
Hey, I just ran the scraper again - doesn't seem to have updated since last time I ran it (~3 months ago). Mind checking if the files are up to date?

**Comment by GregorDeVillain** [comment]
It's perfect, thank you!
